language: python
python:
  - "3.5"
services:
  - mysql
env:
  - mysql_user=root magic_database=cards.sqlite
  - mysql_user=root magic_database=cards
install: pip install -r requirements.txt && ./setup_spellfix.sh
script: pytest
